// import fs from 'fs/promises'
// import path from 'path'
import { Layout } from 'nextra-theme-blog'
// import { collectPageMap } from 'nextra/page-map'

export const metadata = {
  // title: 'Next.js',
  // description: 'Generated by Next.js',
}

export default async function RootLayout({ children }) {
  // const rawJs = await collectPageMap({
  //   dir: path.join(process.cwd(), 'app'),
  //   route: '/'
  // })
  // const pageMapPath = path.join(process.cwd(), 'nextra-page-map.mjs')
  // await fs.writeFile(pageMapPath, rawJs)
  const { pageMap } = await import('../nextra-page-map.mjs')

  return (
    <html lang="en">
      <body>
        <Layout
          pageOpts={{ frontMatter: {}, pageMap }}
          themeConfig={{
            darkMode: true
          }}
        >
          {children}
        </Layout>
      </body>
    </html>
  )
}
