export { default as FeatherIcon } from './feather.svg?svgr'
export { default as LightningIcon } from './lightning.svg?svgr'
export { default as PauseIcon } from './pause.svg?svgr'
export { default as DotsVerticalIcon } from './dots-vertical.svg?svgr'
export { default as BoxIcon } from './box.svg?svgr'
export { default as LayersIcon } from './layers.svg?svgr'
export { default as PulseIcon } from './pulse.svg?svgr'
export { default as RainIcon } from './rain.svg?svgr'
export { default as SwrIcon } from './swr.svg?svgr'
export { default as VercelIcon } from './vercel.svg?svgr'

export { default as CacheImage } from './image.cache.svg?svgr'
export { default as InfiniteImage } from './image.infinite.svg?svgr'
export { default as PaginationImage } from './image.pagination.svg?svgr'
export { default as WelcomeImage } from './image.welcome.svg?svgr'
