import fs from 'fs/promises';
import { Footer, NextraLayout, NextThemesProvider } from 'nextra-theme-docs/client';
import { Banner, Head, Navbar } from 'nextra-theme-docs/server';
import { collectFiles } from 'nextra/page-map';
import type { ComponentProps, ReactElement, ReactNode } from 'react';
import { getDictionary, getDirection } from './_dictionaries/get-dictionary';
import type { Locale } from './_dictionaries/i18n-config';
import 'nextra-theme-docs/style.css';
import './styles.css';
import { getLocale } from './_dictionaries/get-locale';
import { SwrIcon, VercelIcon } from './_icons';
import { pageMap as enPageMap } from '.next/static/chunks/nextra-page-map-en.mjs'
import { pageMap as esPageMap } from '.next/static/chunks/nextra-page-map-es.mjs';
import { pageMap as ruPageMap } from '.next/static/chunks/nextra-page-map-ru.mjs';


export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js'
}

// const localDirs = (await fs.readdir('./docs', { withFileTypes: true }))
//   .filter(dirent => dirent.isDirectory())
//   .map(dirent => dirent.name)

const locales = new Set(['en', 'es', 'ru'])

// const { pageMap } = await collectFiles({
//   dir: './docs',
//   route: '/'
// })

const pageMaps = {
  en: enPageMap,
  es: esPageMap,
  ru: ruPageMap
}

export default async function RootLayout({
  children,
  params
}: {
  children: ReactNode
  params: { lang: Locale }
}) {
  params.lang ||= getLocale()
  const dictionary = await getDictionary(params.lang)
  const lang = locales.has(params.lang) ? params.lang : 'en'
  // const langPageMap = pageMap.find(
  //   item => 'children' in item && item.name === lang
  //   // @ts-expect-error
  // )!.children

  const pageMap = pageMaps[lang]

  return (
    <html
      lang={lang}
      dir={getDirection(lang)}
      // Since next-themes updates that element
      suppressHydrationWarning
    >
      <Head />
      <body>
        <NextThemesProvider attribute="class" disableTransitionOnChange>
          <Banner storageKey="swr-2">SWR 2.0 is out! Read more →</Banner>
          <Navbar
            items={pageMap}
            logo={
              <>
                <SwrIcon className="h-3" />
                <span
                  className="max-md:hidden select-none font-extrabold ltr:ml-2 rtl:mr-2"
                  title={`SWR: ${dictionary.logo.title}`}
                >
                  SWR
                </span>
              </>
            }
          >
            <div>extraContent</div>
          </Navbar>
          <NextraLayout
            pageMap={pageMap}
            docsRepositoryBase="https://github.com/shuding/nextra/blob/core/examples/swr-site"
          >
            {children}
            <Footer>
              <a
                rel="noreferrer"
                target="_blank"
                className="flex items-center gap-2 font-semibold"
                href={dictionary.link.vercel}
              >
                {dictionary.poweredBy} <VercelIcon />
              </a>
            </Footer>
          </NextraLayout>
        </NextThemesProvider>
      </body>
    </html>
  )
}
