export { ReactComponent as ArrowRightIcon } from './arrow-right.svg'
export { ReactComponent as CheckIcon } from './check.svg'
export { ReactComponent as CopyIcon } from './copy.svg'
export { ReactComponent as DiscordIcon } from './discord.svg'
export { ReactComponent as ExpandIcon } from './expand.svg'
export { ReactComponent as GitHubIcon } from './github.svg'
export { ReactComponent as GlobeIcon } from './globe.svg'
export { ReactComponent as GoIcon } from './go.svg'
export { ReactComponent as MenuIcon } from './menu.svg'
export { ReactComponent as MoonIcon } from './moon.svg'
export { ReactComponent as SpinnerIcon } from './spinner.svg'
export { ReactComponent as SunIcon } from './sun.svg'
export { ReactComponent as SvelteIcon } from './svelte.svg'
export { ReactComponent as WordWrapIcon } from './word-wrap.svg'
export { ReactComponent as XIcon } from './x.svg'
export { ReactComponent as JavaScriptIcon } from './javascript.svg'
export { ReactComponent as LinkArrowIcon } from './link-arrow.svg'
export { ReactComponent as TypeScriptIcon } from './typescript.svg'
export { ReactComponent as MarkdownIcon } from './markdown.svg'
export { ReactComponent as MdxIcon } from './mdx.svg'
export { ReactComponent as TerminalIcon } from './terminal.svg'
export { ReactComponent as CssIcon } from './css.svg'
export { ReactComponent as CPPIcon } from './cpp.svg'
export { ReactComponent as CsharpIcon } from './csharp.svg'
export { ReactComponent as GraphQLIcon } from './graphql.svg'
export { ReactComponent as PythonIcon } from './python.svg'
export { ReactComponent as ReactIcon } from './react.svg'
export { ReactComponent as JSONIcon } from './json.svg'
export { ReactComponent as RustIcon } from './rust.svg'
export { ReactComponent as TerraformIcon } from './terraform.svg'
export { ReactComponent as MoveIcon } from './move.svg'
export { ReactComponent as CrossCircledIcon } from './cross-circled.svg'
export { ReactComponent as FileIcon } from './file.svg'
export { ReactComponent as FolderIcon } from './folder.svg'
export { ReactComponent as FolderOpenIcon } from './folder-open.svg'
export { ReactComponent as LinkIcon } from './link.svg'
export {
  ReactComponent as GitHubNoteIcon,
  // Backward compatibility
  ReactComponent as InformationCircleIcon
} from './github-note.svg'
export { ReactComponent as GitHubTipIcon } from './github-tip.svg'
export { ReactComponent as GitHubImportantIcon } from './github-important.svg'
export { ReactComponent as GitHubWarningIcon } from './github-warning.svg'
export { ReactComponent as GitHubCautionIcon } from './github-caution.svg'
